services:
  - type: web
    runtime: python
    name: stockguru
    buildCommand: "./build.sh"
    startCommand: "gunicorn stockguru.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://stockguru.onrender.com"
      - key: PYTHON_VERSION
        value: "3.13.8"
